services:
  # Portainer Agent サービス
  agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    volumes:
      # ホストのDockerソケットをマウントし、環境情報へのアクセスを許可
      - /var/run/docker.sock:/var/run/docker.sock
      # ボリューム、コンテナなど、ホスト上のDockerデータを認識させるため
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      # 外部からのアクセスは不要だが、内部ネットワークで通信するためポートを公開
      - "9001:9001"
    networks:
      - portainer_net

  # Portainer Server サービス
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_server
    command: -H tcp://agent:9001 --tlsskipverify # Agentのサービス名とポートを指定して接続
    restart: always
    volumes:
      # Portainerの設定やデータを永続化
      - portainer_data:/data
    ports:
      # Portainer Web UIへのアクセスポート
      - "9000:9000"
    networks:
      - portainer_net

networks:
  portainer_net:
    # ServerとAgent間の通信用ネットワーク

volumes:
  portainer_data:
